# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mugenmonkey Blog
email: naiyt@mugenmonkey.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for me to talk about random stuff related (perhaps tangentially?) to the
  Mugenmonkey Soulsborne character planners. \[T]/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mugenmonkey.github.io" # the base hostname & protocol for your site
twitter_username: mugenmonkey
repository: mugenmonkey/mugenmonkey.github.io

# Build settings
markdown: kramdown
